### ISSUE TITLE
Showing where the income level is compared to the rest on a graph

### ISSUE THREAD

**Issue by amycesal** [amycesal/50-30-20#24] opened 2016-09-24 19:43 UTC
Some sort of bar graph to show the income distribution of the area, and highlights where the selected number falls in this range.

**Comment by amycesal** [comment] 2016-10-12 03:16
This is being incorporated into the layout as a histogram. 

<img width="415" alt="screen shot 2016-10-11 at 10 15 01 pm" src="https://cloud.githubusercontent.com/assets/1656046/19296316/3fa10998-9000-11e6-868f-34caf7b32d1e.png">

**Comment by danmdoh** [comment] 2016-10-24 19:07
ongoing, reassigning to me

**Comment by danmdoh** [comment] 2016-10-24 22:22
dupe of https://github.com/amycesal/50-30-20/issues/47

**Closed as completed by danmdoh** 2016-10-24 22:22 UTC
Labels: enhancement
